language: python
cache: pip
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install tox codecov sphinx sphinx_rtd_theme
script:
  - tox
  - cd docs
  - make html
after_success:
  - codecov
jobs:
  include:
    - stage: deploy
      script: make doc
      python: 3.6
      env: TOXENV=py36
