build: off

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"
    - PYTHON: "C:\\Python36"
      TOXENV: "docs"
    - PYTHON: "C:\\Python36"
      TOXENV: "lint"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python.exe -m pip install tox codecov"

test_script:
  - "tox"

after_test:
  - "codecov"
