build: off

environment:
  TOXENV:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python.exe -m pip install tox codecov"

test_script:
  - "tox"

after_test:
  - "codecov"
